/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.data_structures;

import java.awt.CardLayout;

/**
 *
 * @author Chan
 */
public class Main_Form extends javax.swing.JFrame {

    /**
     * Creates new form Main_Form
     */
    public Main_Form() {
        initComponents();
        // Crear y agregar los paneles personalizados
        panel_Main.add(new Panel_Inicio(), "Inicio");
        panel_Main.add(new Panel_Secuential_Data(), "Secuential");
        panel_Main.add(new Panel_Matrix(), "Matrix");
        panel_Main.add(new Panel_Linkedlist(), "LinkedList");
        panel_Main.add(new Panel_List_Interface(), "ListInterface");
        panel_Main.add(new Panel_Stack(), "Stack");
        panel_Main.add(new Panel_Queue(), "Queue");
        panel_Main.add(new Panel_Dynamicarray(), "DynamicArray");
        panel_Main.add(new Panel_Tree(), "Tree");
        panel_Main.add(new Panel_Heap(), "Heap");
        CardLayout cl = (CardLayout) panel_Main.getLayout();
        cl.show(panel_Main, "Inicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Buttons = new javax.swing.JPanel();
        btn_Secuentialdata = new javax.swing.JButton();
        btn_Matrix = new javax.swing.JButton();
        btn_Linkedlist = new javax.swing.JButton();
        btn_Listinterface = new javax.swing.JButton();
        btn_Dynamicarray = new javax.swing.JButton();
        btn_Tree = new javax.swing.JButton();
        btn_Queue = new javax.swing.JButton();
        btn_Stack = new javax.swing.JButton();
        btn_Heap = new javax.swing.JButton();
        panel_Main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Secuentialdata.setText("Secuential data");
        btn_Secuentialdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SecuentialdataActionPerformed(evt);
            }
        });

        btn_Matrix.setText("Matrix");
        btn_Matrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MatrixActionPerformed(evt);
            }
        });

        btn_Linkedlist.setText("Linked List");
        btn_Linkedlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LinkedlistActionPerformed(evt);
            }
        });

        btn_Listinterface.setText("List interface");
        btn_Listinterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListinterfaceActionPerformed(evt);
            }
        });

        btn_Dynamicarray.setText("Dynamic array");

        btn_Tree.setText("Tree");

        btn_Queue.setText("Queue");

        btn_Stack.setText("Stack");

        btn_Heap.setText("Heap");

        javax.swing.GroupLayout panel_ButtonsLayout = new javax.swing.GroupLayout(panel_Buttons);
        panel_Buttons.setLayout(panel_ButtonsLayout);
        panel_ButtonsLayout.setHorizontalGroup(
            panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Queue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Secuentialdata, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(btn_Matrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listinterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Linkedlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Stack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Dynamicarray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Tree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Heap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_ButtonsLayout.setVerticalGroup(
            panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Secuentialdata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Matrix, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Listinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Linkedlist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Stack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Queue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Dynamicarray, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Tree, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Heap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Buttons, java.awt.BorderLayout.LINE_START);

        panel_Main.setLayout(new java.awt.CardLayout());
        getContentPane().add(panel_Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SecuentialdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SecuentialdataActionPerformed
        CardLayout cl = (CardLayout) panel_Main.getLayout();
        cl.show(panel_Main, "Secuential");
    }//GEN-LAST:event_btn_SecuentialdataActionPerformed

    private void btn_MatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MatrixActionPerformed
        CardLayout cl = (CardLayout) panel_Main.getLayout();
        cl.show(panel_Main, "Matrix");
    }//GEN-LAST:event_btn_MatrixActionPerformed

    private void btn_ListinterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListinterfaceActionPerformed
        CardLayout cl = (CardLayout) panel_Main.getLayout();
        cl.show(panel_Main, "ListInterface");
    }//GEN-LAST:event_btn_ListinterfaceActionPerformed

    private void btn_LinkedlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LinkedlistActionPerformed
        CardLayout cl = (CardLayout) panel_Main.getLayout();
        cl.show(panel_Main, "LinkedList");
    }//GEN-LAST:event_btn_LinkedlistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Dynamicarray;
    private javax.swing.JButton btn_Heap;
    private javax.swing.JButton btn_Linkedlist;
    private javax.swing.JButton btn_Listinterface;
    private javax.swing.JButton btn_Matrix;
    private javax.swing.JButton btn_Queue;
    private javax.swing.JButton btn_Secuentialdata;
    private javax.swing.JButton btn_Stack;
    private javax.swing.JButton btn_Tree;
    private javax.swing.JPanel panel_Buttons;
    private javax.swing.JPanel panel_Main;
    // End of variables declaration//GEN-END:variables
}
