/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.data_structures;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Chan
 */
public class Panel_Secuential_Data extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Secuential_Data
     */
    
    private final ArrayList<String> dataList = new ArrayList<>();
    
    public Panel_Secuential_Data() {
        initComponents();
        refreshPanelData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        txt_Value = new javax.swing.JTextField();
        lbl__Entervalue = new javax.swing.JLabel();
        btn_Add = new javax.swing.JButton();
        btn_Remove = new javax.swing.JButton();
        lbl__Data = new javax.swing.JLabel();
        panel_Data = new javax.swing.JPanel();
        lbl__Index = new javax.swing.JLabel();
        lbl__Result = new javax.swing.JLabel();
        txt_Index = new javax.swing.JTextField();
        txt_Result = new javax.swing.JTextField();
        btn_Getvalue = new javax.swing.JButton();

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Secuential Data");

        txt_Value.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl__Entervalue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl__Entervalue.setText("Enter value:");

        btn_Add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Remove.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Remove.setText("Remove");
        btn_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoveActionPerformed(evt);
            }
        });

        lbl__Data.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl__Data.setText("Data:");

        javax.swing.GroupLayout panel_DataLayout = new javax.swing.GroupLayout(panel_Data);
        panel_Data.setLayout(panel_DataLayout);
        panel_DataLayout.setHorizontalGroup(
            panel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        panel_DataLayout.setVerticalGroup(
            panel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        lbl__Index.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl__Index.setText("Index:");

        lbl__Result.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl__Result.setText("Result");

        txt_Index.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_Result.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_Getvalue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Getvalue.setText("Get value");
        btn_Getvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GetvalueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl__Index, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Index, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Getvalue))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl__Data, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl__Entervalue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Add)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Remove))
                                .addComponent(panel_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl__Result, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl__Entervalue)
                    .addComponent(btn_Add)
                    .addComponent(btn_Remove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl__Data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl__Index)
                    .addComponent(txt_Index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Getvalue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl__Result)
                    .addComponent(txt_Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        String value = txt_Value.getText().trim();
        if (!value.isEmpty()) {
            dataList.add(value);
            txt_Value.setText("");
            refreshPanelData();
        }
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_GetvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GetvalueActionPerformed
        try {
            int index = Integer.parseInt(txt_Index.getText());
            if (index >= 0 && index < dataList.size()) {
                txt_Result.setText(dataList.get(index));
            } else {
                txt_Result.setText("Invalid index");
            }
        } catch (NumberFormatException e) {
            txt_Result.setText("Enter number");
        }
    }//GEN-LAST:event_btn_GetvalueActionPerformed

    private void btn_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoveActionPerformed
        String value = txt_Value.getText().trim();
        if (!value.isEmpty()) {
            dataList.remove(value); // elimina la primera coincidencia
            txt_Value.setText("");
            refreshPanelData();
        }

    }//GEN-LAST:event_btn_RemoveActionPerformed

    private void refreshPanelData() {
        panel_Data.removeAll();
        for (String item : dataList) {
            JLabel label = new JLabel(item);
            label.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
            panel_Data.add(label);
        }
        panel_Data.revalidate();
        panel_Data.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Getvalue;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl__Data;
    private javax.swing.JLabel lbl__Entervalue;
    private javax.swing.JLabel lbl__Index;
    private javax.swing.JLabel lbl__Result;
    private javax.swing.JPanel panel_Data;
    private javax.swing.JTextField txt_Index;
    private javax.swing.JTextField txt_Result;
    private javax.swing.JTextField txt_Value;
    // End of variables declaration//GEN-END:variables
}
