/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.data_structures;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author Chan
 */
public class Panel_Queue extends javax.swing.JPanel {
    
    private Queue<String> queue = new LinkedList<>();
    
    /**
     * Creates new form Panel_Queue
     */
    public Panel_Queue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Value = new javax.swing.JTextField();
        btn_Llegar = new javax.swing.JButton();
        btn_Atender = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_Values = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Queue");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        txt_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ValueActionPerformed(evt);
            }
        });

        btn_Llegar.setText("Llegar");
        btn_Llegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LlegarActionPerformed(evt);
            }
        });

        btn_Atender.setText("Atender");
        btn_Atender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtenderActionPerformed(evt);
            }
        });

        txtArea_Values.setColumns(20);
        txtArea_Values.setRows(5);
        jScrollPane1.setViewportView(txtArea_Values);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_Llegar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Atender, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(txt_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Llegar)
                    .addComponent(btn_Atender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarVistaCola() {
        if (queue.isEmpty()) {
            txtArea_Values.setText("No hay personas en la cola.");
            return;
        }
        StringBuilder sb = new StringBuilder();
        for (String nombre : queue) {
            sb.append(nombre).append("\n");
        }
        txtArea_Values.setText(sb.toString());
    }
    
    private void btn_LlegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LlegarActionPerformed
        String nombre = txt_Value.getText().trim();
        if (!nombre.isEmpty()) {
            queue.add(nombre);
            txt_Value.setText("");
            actualizarVistaCola();
        } else {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
        }
    }//GEN-LAST:event_btn_LlegarActionPerformed

    private void btn_AtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtenderActionPerformed
        if (!queue.isEmpty()) {
            String atendido = queue.poll();
            JOptionPane.showMessageDialog(this, "Atendiendo a: " + atendido);
            actualizarVistaCola();
        } else {
            JOptionPane.showMessageDialog(this, "No hay personas en la cola.");
        }
    }//GEN-LAST:event_btn_AtenderActionPerformed

    private void txt_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ValueActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atender;
    private javax.swing.JButton btn_Llegar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea_Values;
    private javax.swing.JTextField txt_Value;
    // End of variables declaration//GEN-END:variables
}
